env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - plugin:security/recommended
  - plugin:import/recommended
parserOptions:
  ecmaVersion: latest
rules: {}
overrides:
  - files:
      - "*.js"
      - "*.mjs"
    rules:
      no-underscore-dangle:
        - error
        - allow:
            - _id
      linebreak-style: off
      import/prefer-default-export: off
      import/no-extraneous-dependencies: off
      no-unused-vars:
        - error
        - args: none
